version: '3.8'

services:
  django:
    build: ./server
    env_file:
      - .env.prod.server
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    env_file:
      - .env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

  frontend:
    build: ./frontend
    env_file:
      - .env.prod.frontend
    depends_on:
      - django
    networks:
      - app-network
    ports:
      - 3000:3000

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 5000:5000
    networks:
      - app-network
    depends_on:
      - django
      - frontend


volumes:
  postgres_data:
  static_volume:

networks:
  app-network:
    driver: bridge