# Generated by Django 4.2.2 on 2023-06-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_list_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='API.tag'),
        ),
    ]
