# Generated by Django 4.2.2 on 2023-06-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_task_author_alter_task_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='list',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
