# Generated by Django 4.2.2 on 2023-06-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_list_options_list_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
    ]
